### ISSUE TITLE
Npm run setup throwing dependency errors

### ISSUE THREAD

**Issue by therobertos007** [epicweb-dev/react-performance#133]
Hi!

When running the ```npm run setup``` command for this repository, I get many errors that prevent the process from completing. This happens only for this repository. For all others, everything works fine:

Logs:

```
▶️  Starting workshop setup...
      Running the following command: npx --yes "https://gist.github.com/kentcdodds/bb452ffe53a5caa3600197e1d8005733" -q
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! must not have multiple workspaces with the same name
npm ERR! package 'types-react-dom' has conflicts in the following paths:
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.problem.lazy\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.solution.lazy\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.problem.eager\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.solution.eager\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.problem.transition\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.solution.transition\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.problem.use-memo\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.solution.use-memo\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.problem.worker\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.solution.worker\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.problem.async\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.solution.async\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.problem.memo\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.solution.memo\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.problem.comparator\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.solution.comparator\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.problem.primitives\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.solution.primitives\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.problem.virtualizer\node_modules\@types\react-dom
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.solution.virtualizer\node_modules\@types\react-dom
npm ERR! package 'types-react' has conflicts in the following paths:
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.problem.lazy\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.solution.lazy\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.problem.eager\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.solution.eager\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.problem.transition\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.solution.transition\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.problem.use-memo\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.solution.use-memo\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.problem.worker\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.solution.worker\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.problem.async\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.solution.async\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.problem.memo\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.solution.memo\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.problem.comparator\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.solution.comparator\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.problem.primitives\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.solution.primitives\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.problem.virtualizer\node_modules\@types\react
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.solution.virtualizer\node_modules\@types\react
npm ERR! package 'react-dom' has conflicts in the following paths:
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.problem.lazy\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.solution.lazy\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.problem.eager\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.solution.eager\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.problem.transition\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.solution.transition\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.problem.use-memo\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.solution.use-memo\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.problem.worker\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.solution.worker\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.problem.async\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.solution.async\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.problem.memo\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.solution.memo\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.problem.comparator\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.solution.comparator\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.problem.primitives\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.solution.primitives\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.problem.virtualizer\node_modules\react-dom
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.solution.virtualizer\node_modules\react-dom
npm ERR! package 'react' has conflicts in the following paths:
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.problem.lazy\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\01.solution.lazy\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.problem.eager\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\02.solution.eager\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.problem.transition\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\04.code-splitting\03.solution.transition\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.problem.use-memo\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\01.solution.use-memo\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.problem.worker\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\02.solution.worker\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.problem.async\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\05.calculations\03.solution.async\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.problem.memo\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\01.solution.memo\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.problem.comparator\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\02.solution.comparator\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.problem.primitives\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\06.rerenders\03.solution.primitives\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.problem.virtualizer\node_modules\react
npm ERR!     MY PATH\react-performance\exercises\07.windowing\01.solution.virtualizer\node_modules\react
```

**Comment by kentcdodds** [comment]
Thanks for opening this issue. I missed a couple spots when updating dependencies. It should be fixed now. It should work once you run:

```
npx update-epic-workshop 
```

**Comment by therobertos007** [comment]
Hi @kentcdodds,

Thanks for your reply. Unfortunately problem still occurs on my env.
Clonning repo and setting it up from beginning doesn't work. Also ``` npx update-epic-workshop ``` didn't help. In my console I can still see the same output with errors.

Not sure if there is something wrong with my steps or problem still exists.

**Comment by kentcdodds** [comment]
Could you try to set it up from scratch?

**Comment by therobertos007** [comment]
Hi!

I started from scratch many times. Also trying different paths etc.

After cloning the repo with ```git clone --depth 1 https://github.com/epicweb-dev/react-performance.git``` and goes to the the folder. I'm running ```npm run setup``` and my output is the same as in the opened issue.

After running ```npx update-epic-workshop``` I'm also getting errors like this:

```
npm ERR! code EDUPLICATEWORKSPACE
npm ERR! must not have multiple workspaces with the same name
npm ERR! package 'types-react-dom' has conflicts in the following paths:
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\01.problem.lazy\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\01.solution.lazy\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\02.problem.eager\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\02.solution.eager\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\03.problem.transition\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\03.solution.transition\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\01.problem.use-memo\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\01.solution.use-memo\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\02.problem.worker\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\02.solution.worker\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\03.problem.async\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\03.solution.async\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\01.problem.memo\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\01.solution.memo\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\02.problem.comparator\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\02.solution.comparator\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\03.problem.primitives\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\03.solution.primitives\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\07.windowing\01.problem.virtualizer\node_modules\@types\react-dom
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\07.windowing\01.solution.virtualizer\node_modules\@types\react-dom
npm ERR! package 'types-react' has conflicts in the following paths:
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\01.problem.lazy\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\01.solution.lazy\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\02.problem.eager\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\02.solution.eager\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\03.problem.transition\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\04.code-splitting\03.solution.transition\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\01.problem.use-memo\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\01.solution.use-memo\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\02.problem.worker\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\02.solution.worker\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\03.problem.async\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\05.calculations\03.solution.async\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\01.problem.memo\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\01.solution.memo\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\02.problem.comparator\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\02.solution.comparator\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\03.problem.primitives\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\06.rerenders\03.solution.primitives\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\07.windowing\01.problem.virtualizer\node_modules\@types\react
npm ERR!     MY_PATH\Code\EpicReact19\react-performance-worshop\exercises\07.windowing\01.solution.virtualizer\node_modules\@types\react
```


It doesn't matter which command I run first, or did I run only one - output is the same.
As mentioned before - it's extra weird because all the rest of the workshops works and set up without any problems.

**Comment by therobertos007** [comment]
Both solutions didn't work. Still throwing an errors for ```types-react-dom``` and ```types-react```.

**Comment by kentcdodds** [comment]
Dang. I have no idea why those are showing up in the package-lock.json. I've removed them completely from the project and regenerated the lockfile. Super weird. I'll keep looking at it. Sorry for the trouble!

**Comment by kentcdodds** [comment]
Ah! I figured it out! Try again. This time I'm 99% sure it'll work.

**Comment by therobertos007** [comment]
It's working! 

Thank you so much for your time and help! 😄

**Comment by kentcdodds** [comment]
Thank you for your patience! I'm glad it's working now :)
